/**
 * Initial demo universe — portfolio preview only (large seeded dataset).
 */
import type {
  Activity,
  Membership,
  OrganizationWithRole,
  PendingInvite,
  Project,
  Task,
  User,
} from '@/types';
import { EventType, Role, TaskPriority, TaskStatus } from '@/types';
import type { Notification } from '@/lib/api/notifications.api';
import { DEMO_IDS } from '@/lib/demo/demo-ids';

function isoDaysAgo(days: number, hour = 10, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export interface DemoSeedState {
  user: User;
  organizations: OrganizationWithRole[];
  projects: Project[];
  tasks: Task[];
  memberships: Membership[];
  invites: PendingInvite[];
  activities: Activity[];
  notifications: Notification[];
}

type TeammateKey = keyof typeof DEMO_IDS.teammates;

function resolveMemberId(
  alexId: string,
  key: 'alex' | TeammateKey | null,
  map: Record<TeammateKey, string>,
): string | null {
  if (key === null) return null;
  if (key === 'alex') return alexId;
  return map[key];
}

interface TaskRow {
  id: string;
  title: string;
  description: string | null;
  projectId: string;
  status: TaskStatus;
  priority: TaskPriority;
  assignee: 'alex' | TeammateKey | null;
  createdDaysAgo: number;
  updatedDaysAgo: number;
  /** Days from today; negative = future due date */
  dueDaysOffset?: number | null;
}

export function buildDemoSeed(loginEmail: string): DemoSeedState {
  const now = new Date().toISOString();
  const orgId = DEMO_IDS.org;
  const alexId = DEMO_IDS.user;
  const P = DEMO_IDS.projects;
  const M = DEMO_IDS.teammates;

  const user: User = {
    id: alexId,
    email: loginEmail.trim() || 'alex.chen@acme.demo',
    firstName: 'Alex',
    lastName: 'Chen',
    isEmailVerified: true,
    status: 'active',
    currentOrganizationId: orgId,
    createdAt: isoDaysAgo(120),
  };

  const organizations: OrganizationWithRole[] = [
    {
      id: orgId,
      name: 'Acme Product Team',
      slug: 'acme-product-team',
      createdBy: alexId,
      createdAt: isoDaysAgo(90),
      updatedAt: now,
      role: Role.ADMIN,
    },
  ];

  const projects: Project[] = [
    {
      id: P.websiteRedesign,
      organizationId: orgId,
      name: 'Website Redesign',
      description: 'Marketing site refresh with design system rollout and CMS migration.',
      createdBy: alexId,
      createdAt: isoDaysAgo(45, 9),
      updatedAt: isoDaysAgo(1, 15),
    },
    {
      id: P.mobileLaunch,
      organizationId: orgId,
      name: 'Mobile App Launch',
      description: 'iOS/Android MVP, push notifications, and App Store assets.',
      createdBy: M.sam,
      createdAt: isoDaysAgo(38, 11),
      updatedAt: isoDaysAgo(0, 14),
    },
    {
      id: P.designSystem,
      organizationId: orgId,
      name: 'Design System 2.0',
      description: 'Tokens, components, Storybook, and Figma library parity.',
      createdBy: M.jordan,
      createdAt: isoDaysAgo(28, 14),
      updatedAt: isoDaysAgo(2, 10),
    },
    {
      id: P.apiPlatform,
      organizationId: orgId,
      name: 'API Platform',
      description: 'REST v2, rate limits, webhooks, and partner documentation.',
      createdBy: M.priya,
      createdAt: isoDaysAgo(22, 8),
      updatedAt: isoDaysAgo(1, 9),
    },
    {
      id: P.growthQ2,
      organizationId: orgId,
      name: 'Growth Experiments Q2',
      description: 'A/B tests, referral loop, and onboarding analytics.',
      createdBy: M.marcus,
      createdAt: isoDaysAgo(18, 10),
      updatedAt: isoDaysAgo(3, 16),
    },
    {
      id: P.internalOps,
      organizationId: orgId,
      name: 'Internal Ops & Tooling',
      description: 'Support macros, admin dashboards, and incident runbooks.',
      createdBy: M.elena,
      createdAt: isoDaysAgo(12, 13),
      updatedAt: isoDaysAgo(0, 11),
    },
  ];

  const taskRows: TaskRow[] = [
    // Website Redesign
    {
      id: 'demo-task-hero-concepts',
      title: 'Draft homepage hero concepts',
      description: 'Three visual directions with motion notes.',
      projectId: P.websiteRedesign,
      status: TaskStatus.TODO,
      priority: TaskPriority.HIGH,
      assignee: 'alex',
      createdDaysAgo: 14,
      updatedDaysAgo: 2,
      dueDaysOffset: -4,
    },
    {
      id: 'demo-task-design-audit',
      title: 'Design system audit',
      description: 'Inventory components vs Figma library.',
      projectId: P.websiteRedesign,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.MEDIUM,
      assignee: 'jordan',
      createdDaysAgo: 21,
      updatedDaysAgo: 0,
    },
    {
      id: 'demo-task-kickoff-notes',
      title: 'Kickoff workshop notes',
      description: null,
      projectId: P.websiteRedesign,
      status: TaskStatus.DONE,
      priority: TaskPriority.LOW,
      assignee: 'alex',
      createdDaysAgo: 35,
      updatedDaysAgo: 28,
      dueDaysOffset: 20,
    },
    {
      id: 'demo-task-cms-migration',
      title: 'CMS content migration dry run',
      description: 'Export legacy WordPress → structured JSON.',
      projectId: P.websiteRedesign,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.HIGH,
      assignee: 'sam',
      createdDaysAgo: 9,
      updatedDaysAgo: 1,
      dueDaysOffset: -2,
    },
    {
      id: 'demo-task-seo-pricing',
      title: 'SEO audit — pricing pages',
      description: 'Meta, schema.org, Core Web Vitals.',
      projectId: P.websiteRedesign,
      status: TaskStatus.TODO,
      priority: TaskPriority.MEDIUM,
      assignee: 'marcus',
      createdDaysAgo: 7,
      updatedDaysAgo: 7,
      dueDaysOffset: -10,
    },
    {
      id: 'demo-task-case-studies',
      title: 'Customer case study templates',
      description: null,
      projectId: P.websiteRedesign,
      status: TaskStatus.TODO,
      priority: TaskPriority.LOW,
      assignee: null,
      createdDaysAgo: 5,
      updatedDaysAgo: 5,
    },
    {
      id: 'demo-task-analytics',
      title: 'Analytics instrumentation plan',
      description: 'Events for funnel and conversion.',
      projectId: P.websiteRedesign,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.MEDIUM,
      assignee: 'priya',
      createdDaysAgo: 11,
      updatedDaysAgo: 3,
    },
    {
      id: 'demo-task-locale-fr',
      title: 'French locale — legal pages',
      description: 'Coordinate with counsel on disclaimers.',
      projectId: P.websiteRedesign,
      status: TaskStatus.TODO,
      priority: TaskPriority.URGENT,
      assignee: 'elena',
      createdDaysAgo: 4,
      updatedDaysAgo: 4,
      dueDaysOffset: -1,
    },
    {
      id: 'demo-task-blog-rss',
      title: 'Blog RSS + canonical URLs',
      description: null,
      projectId: P.websiteRedesign,
      status: TaskStatus.DONE,
      priority: TaskPriority.MEDIUM,
      assignee: 'sam',
      createdDaysAgo: 30,
      updatedDaysAgo: 12,
    },
    {
      id: 'demo-task-accessibility-audit',
      title: 'WCAG 2.2 AA audit remediation',
      description: 'Focus order, contrast, live regions.',
      projectId: P.websiteRedesign,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.HIGH,
      assignee: 'jordan',
      createdDaysAgo: 16,
      updatedDaysAgo: 4,
    },
    {
      id: 'demo-task-video-embed',
      title: 'Lazy-load homepage video embed',
      description: null,
      projectId: P.websiteRedesign,
      status: TaskStatus.TODO,
      priority: TaskPriority.LOW,
      assignee: 'riley',
      createdDaysAgo: 3,
      updatedDaysAgo: 3,
    },
    {
      id: 'demo-task-forms-spam',
      title: 'Contact form honeypot + Turnstile',
      description: 'Reduce spam without hurting conversion.',
      projectId: P.websiteRedesign,
      status: TaskStatus.DONE,
      priority: TaskPriority.MEDIUM,
      assignee: 'alex',
      createdDaysAgo: 26,
      updatedDaysAgo: 8,
    },
    // Mobile App Launch
    {
      id: 'demo-task-api-contract',
      title: 'API contract review',
      description: 'Align REST payloads with mobile clients.',
      projectId: P.mobileLaunch,
      status: TaskStatus.TODO,
      priority: TaskPriority.URGENT,
      assignee: 'sam',
      createdDaysAgo: 12,
      updatedDaysAgo: 3,
      dueDaysOffset: -3,
    },
    {
      id: 'demo-task-beta-signup',
      title: 'Beta signup flow',
      description: 'Waitlist + email confirmation UX.',
      projectId: P.mobileLaunch,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.HIGH,
      assignee: 'alex',
      createdDaysAgo: 18,
      updatedDaysAgo: 0,
    },
    {
      id: 'demo-task-mvp-scope',
      title: 'Define MVP scope',
      description: null,
      projectId: P.mobileLaunch,
      status: TaskStatus.DONE,
      priority: TaskPriority.MEDIUM,
      assignee: 'sam',
      createdDaysAgo: 40,
      updatedDaysAgo: 25,
    },
    {
      id: 'demo-task-push-cert',
      title: 'APNs & FCM credentials rotation',
      description: 'Store secrets in vault; document rollover.',
      projectId: P.mobileLaunch,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.URGENT,
      assignee: 'priya',
      createdDaysAgo: 8,
      updatedDaysAgo: 1,
    },
    {
      id: 'demo-task-offline-sync',
      title: 'Offline queue + conflict resolution',
      description: null,
      projectId: P.mobileLaunch,
      status: TaskStatus.TODO,
      priority: TaskPriority.HIGH,
      assignee: 'sam',
      createdDaysAgo: 6,
      updatedDaysAgo: 6,
    },
    {
      id: 'demo-task-app-store-copy',
      title: 'App Store / Play copy & screenshots',
      description: 'Localized EN + DE.',
      projectId: P.mobileLaunch,
      status: TaskStatus.TODO,
      priority: TaskPriority.MEDIUM,
      assignee: 'marcus',
      createdDaysAgo: 10,
      updatedDaysAgo: 10,
      dueDaysOffset: -14,
    },
    {
      id: 'demo-task-crashlytics',
      title: 'Crashlytics symbolication pipeline',
      description: null,
      projectId: P.mobileLaunch,
      status: TaskStatus.DONE,
      priority: TaskPriority.MEDIUM,
      assignee: 'riley',
      createdDaysAgo: 22,
      updatedDaysAgo: 9,
    },
    {
      id: 'demo-task-biometric',
      title: 'Biometric login polish',
      description: 'Fallback when Face ID denied.',
      projectId: P.mobileLaunch,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.LOW,
      assignee: 'jordan',
      createdDaysAgo: 13,
      updatedDaysAgo: 2,
    },
    {
      id: 'demo-task-deep-links',
      title: 'Universal links & deferred deep linking',
      description: 'Branch.io evaluation.',
      projectId: P.mobileLaunch,
      status: TaskStatus.TODO,
      priority: TaskPriority.HIGH,
      assignee: null,
      createdDaysAgo: 4,
      updatedDaysAgo: 4,
    },
    {
      id: 'demo-task-beta-feedback',
      title: 'Beta tester feedback triage',
      description: 'Slack → Linear import rules.',
      projectId: P.mobileLaunch,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.MEDIUM,
      assignee: 'elena',
      createdDaysAgo: 5,
      updatedDaysAgo: 0,
    },
    {
      id: 'demo-task-perf-budget',
      title: 'Mobile perf budget — cold start',
      description: 'Target <2s on mid-tier Android.',
      projectId: P.mobileLaunch,
      status: TaskStatus.DONE,
      priority: TaskPriority.HIGH,
      assignee: 'sam',
      createdDaysAgo: 28,
      updatedDaysAgo: 11,
    },
    // Design System 2.0
    {
      id: 'demo-task-ds-tokens',
      title: 'Semantic color tokens (dark mode)',
      description: null,
      projectId: P.designSystem,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.HIGH,
      assignee: 'jordan',
      createdDaysAgo: 19,
      updatedDaysAgo: 1,
    },
    {
      id: 'demo-task-ds-data-grid',
      title: 'Data grid component — virtualization',
      description: 'Keyboard nav parity with spreadsheet norms.',
      projectId: P.designSystem,
      status: TaskStatus.TODO,
      priority: TaskPriority.MEDIUM,
      assignee: 'riley',
      createdDaysAgo: 7,
      updatedDaysAgo: 7,
    },
    {
      id: 'demo-task-ds-changelog',
      title: 'Storybook changelog automation',
      description: 'Changesets + Slack digest.',
      projectId: P.designSystem,
      status: TaskStatus.TODO,
      priority: TaskPriority.LOW,
      assignee: 'alex',
      createdDaysAgo: 4,
      updatedDaysAgo: 4,
    },
    {
      id: 'demo-task-ds-icons',
      title: 'Icon set consolidation (192→96)',
      description: null,
      projectId: P.designSystem,
      status: TaskStatus.DONE,
      priority: TaskPriority.MEDIUM,
      assignee: 'jordan',
      createdDaysAgo: 24,
      updatedDaysAgo: 6,
    },
    {
      id: 'demo-task-ds-forms',
      title: 'Form field anatomy — error states',
      description: 'Assistive text patterns.',
      projectId: P.designSystem,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.MEDIUM,
      assignee: 'jordan',
      createdDaysAgo: 14,
      updatedDaysAgo: 3,
    },
    {
      id: 'demo-task-ds-release',
      title: 'v2.0 release comms',
      description: 'Email + webinar deck.',
      projectId: P.designSystem,
      status: TaskStatus.TODO,
      priority: TaskPriority.LOW,
      assignee: 'marcus',
      createdDaysAgo: 2,
      updatedDaysAgo: 2,
      dueDaysOffset: -7,
    },
    {
      id: 'demo-task-ds-figma-sync',
      title: 'Figma ↔ code drift report',
      description: null,
      projectId: P.designSystem,
      status: TaskStatus.TODO,
      priority: TaskPriority.MEDIUM,
      assignee: null,
      createdDaysAgo: 6,
      updatedDaysAgo: 6,
    },
    {
      id: 'demo-task-ds-a11y-checklist',
      title: 'Component a11y acceptance checklist',
      description: 'Embed in PR template.',
      projectId: P.designSystem,
      status: TaskStatus.DONE,
      priority: TaskPriority.HIGH,
      assignee: 'elena',
      createdDaysAgo: 17,
      updatedDaysAgo: 5,
    },
    // API Platform
    {
      id: 'demo-task-api-openapi',
      title: 'OpenAPI 3.1 publish pipeline',
      description: 'Redoc + Try-it console.',
      projectId: P.apiPlatform,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.HIGH,
      assignee: 'priya',
      createdDaysAgo: 15,
      updatedDaysAgo: 1,
    },
    {
      id: 'demo-task-api-rate-limit',
      title: 'Per-tenant rate limits',
      description: 'Redis sliding window + burst.',
      projectId: P.apiPlatform,
      status: TaskStatus.TODO,
      priority: TaskPriority.URGENT,
      assignee: 'priya',
      createdDaysAgo: 9,
      updatedDaysAgo: 9,
      dueDaysOffset: -5,
    },
    {
      id: 'demo-task-api-webhooks',
      title: 'Webhook signing & replay protection',
      description: null,
      projectId: P.apiPlatform,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.MEDIUM,
      assignee: 'sam',
      createdDaysAgo: 11,
      updatedDaysAgo: 2,
    },
    {
      id: 'demo-task-api-deprecation',
      title: 'v1 sunset timeline comms',
      description: 'Partner email + status page.',
      projectId: P.apiPlatform,
      status: TaskStatus.TODO,
      priority: TaskPriority.MEDIUM,
      assignee: 'marcus',
      createdDaysAgo: 6,
      updatedDaysAgo: 6,
    },
    {
      id: 'demo-task-api-sandbox',
      title: 'Sandbox API keys lifecycle',
      description: 'Auto-expire after 90d.',
      projectId: P.apiPlatform,
      status: TaskStatus.DONE,
      priority: TaskPriority.LOW,
      assignee: 'riley',
      createdDaysAgo: 20,
      updatedDaysAgo: 7,
    },
    {
      id: 'demo-task-api-partner-auth',
      title: 'OAuth2 client credentials for partners',
      description: null,
      projectId: P.apiPlatform,
      status: TaskStatus.TODO,
      priority: TaskPriority.HIGH,
      assignee: 'priya',
      createdDaysAgo: 5,
      updatedDaysAgo: 5,
    },
    {
      id: 'demo-task-api-observability',
      title: 'Trace sampling tune (hot paths)',
      description: 'Reduce cost 30%.',
      projectId: P.apiPlatform,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.MEDIUM,
      assignee: 'elena',
      createdDaysAgo: 8,
      updatedDaysAgo: 0,
    },
    {
      id: 'demo-task-api-error-codes',
      title: 'Standard error envelope rollout',
      description: 'code, message, fieldErrors.',
      projectId: P.apiPlatform,
      status: TaskStatus.DONE,
      priority: TaskPriority.HIGH,
      assignee: 'priya',
      createdDaysAgo: 25,
      updatedDaysAgo: 10,
    },
    // Growth Q2
    {
      id: 'demo-task-grw-experiment-hero',
      title: 'Experiment #142 — hero CTA copy',
      description: 'Stats engine + guardrails.',
      projectId: P.growthQ2,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.HIGH,
      assignee: 'marcus',
      createdDaysAgo: 10,
      updatedDaysAgo: 1,
    },
    {
      id: 'demo-task-grw-referral',
      title: 'Referral loop v2 — double-sided reward',
      description: null,
      projectId: P.growthQ2,
      status: TaskStatus.TODO,
      priority: TaskPriority.MEDIUM,
      assignee: 'marcus',
      createdDaysAgo: 8,
      updatedDaysAgo: 8,
    },
    {
      id: 'demo-task-grw-onboarding',
      title: 'Onboarding checklist analytics',
      description: 'Drop-off by step.',
      projectId: P.growthQ2,
      status: TaskStatus.DONE,
      priority: TaskPriority.MEDIUM,
      assignee: 'alex',
      createdDaysAgo: 21,
      updatedDaysAgo: 12,
    },
    {
      id: 'demo-task-grw-email-drip',
      title: 'Lifecycle email drip — week 1',
      description: 'Copy review with brand.',
      projectId: P.growthQ2,
      status: TaskStatus.TODO,
      priority: TaskPriority.LOW,
      assignee: 'elena',
      createdDaysAgo: 4,
      updatedDaysAgo: 4,
    },
    {
      id: 'demo-task-grw-segment-sync',
      title: 'Segment ↔ warehouse sync health',
      description: null,
      projectId: P.growthQ2,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.MEDIUM,
      assignee: 'priya',
      createdDaysAgo: 7,
      updatedDaysAgo: 2,
    },
    {
      id: 'demo-task-grw-pricing-test',
      title: 'Pricing page micro-test',
      description: 'Annual vs monthly default.',
      projectId: P.growthQ2,
      status: TaskStatus.TODO,
      priority: TaskPriority.LOW,
      assignee: null,
      createdDaysAgo: 3,
      updatedDaysAgo: 3,
    },
    // Internal Ops
    {
      id: 'demo-task-ops-runbook',
      title: 'Incident runbook — payment failures',
      description: 'PagerDuty + Stripe dashboard links.',
      projectId: P.internalOps,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.HIGH,
      assignee: 'elena',
      createdDaysAgo: 9,
      updatedDaysAgo: 1,
    },
    {
      id: 'demo-task-ops-macros',
      title: 'Support macro refresh (50 templates)',
      description: null,
      projectId: P.internalOps,
      status: TaskStatus.TODO,
      priority: TaskPriority.MEDIUM,
      assignee: 'riley',
      createdDaysAgo: 6,
      updatedDaysAgo: 6,
    },
    {
      id: 'demo-task-ops-admin-audit',
      title: 'Admin action audit log UI',
      description: 'Filter by actor + entity.',
      projectId: P.internalOps,
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.MEDIUM,
      assignee: 'alex',
      createdDaysAgo: 11,
      updatedDaysAgo: 0,
    },
    {
      id: 'demo-task-ops-sla',
      title: 'SLA breach dashboards',
      description: null,
      projectId: P.internalOps,
      status: TaskStatus.DONE,
      priority: TaskPriority.LOW,
      assignee: 'elena',
      createdDaysAgo: 18,
      updatedDaysAgo: 4,
    },
    {
      id: 'demo-task-ops-data-export',
      title: 'GDPR data export job monitoring',
      description: 'Alert if queue > 1h.',
      projectId: P.internalOps,
      status: TaskStatus.TODO,
      priority: TaskPriority.URGENT,
      assignee: 'priya',
      createdDaysAgo: 5,
      updatedDaysAgo: 5,
      dueDaysOffset: -2,
    },
    {
      id: 'demo-task-ops-access-review',
      title: 'Quarterly access review — contractors',
      description: null,
      projectId: P.internalOps,
      status: TaskStatus.TODO,
      priority: TaskPriority.MEDIUM,
      assignee: 'alex',
      createdDaysAgo: 2,
      updatedDaysAgo: 2,
    },
  ];

  const tasks: Task[] = taskRows.map((row) => {
    const assigneeId = resolveMemberId(alexId, row.assignee, M);
    let dueDate: string | null = null;
    if (row.dueDaysOffset !== undefined && row.dueDaysOffset !== null) {
      dueDate = isoDaysAgo(-row.dueDaysOffset, 18);
    }
    return {
      id: row.id,
      projectId: row.projectId,
      organizationId: orgId,
      title: row.title,
      description: row.description,
      status: row.status,
      priority: row.priority,
      assignedTo: assigneeId,
      dueDate,
      createdBy: alexId,
      createdAt: isoDaysAgo(row.createdDaysAgo, 10 + (row.id.length % 8)),
      updatedAt: isoDaysAgo(row.updatedDaysAgo, 14 + (row.id.length % 7)),
    };
  });

  const memberships: Membership[] = [
    {
      id: 'demo-mem-alex',
      userId: alexId,
      organizationId: orgId,
      role: Role.ADMIN,
      createdAt: isoDaysAgo(90),
      user: {
        id: alexId,
        email: user.email,
        firstName: 'Alex',
        lastName: 'Chen',
        status: 'active',
      },
    },
    {
      id: 'demo-mem-sam',
      userId: M.sam,
      organizationId: orgId,
      role: Role.MEMBER,
      createdAt: isoDaysAgo(88),
      user: {
        id: M.sam,
        email: 'sam.rivera@acme.demo',
        firstName: 'Sam',
        lastName: 'Rivera',
        status: 'active',
      },
    },
    {
      id: 'demo-mem-jordan',
      userId: M.jordan,
      organizationId: orgId,
      role: Role.MEMBER,
      createdAt: isoDaysAgo(86),
      user: {
        id: M.jordan,
        email: 'jordan.lee@acme.demo',
        firstName: 'Jordan',
        lastName: 'Lee',
        status: 'active',
      },
    },
    {
      id: 'demo-mem-priya',
      userId: M.priya,
      organizationId: orgId,
      role: Role.MEMBER,
      createdAt: isoDaysAgo(62),
      user: {
        id: M.priya,
        email: 'priya.shah@acme.demo',
        firstName: 'Priya',
        lastName: 'Shah',
        status: 'active',
      },
    },
    {
      id: 'demo-mem-marcus',
      userId: M.marcus,
      organizationId: orgId,
      role: Role.MEMBER,
      createdAt: isoDaysAgo(55),
      user: {
        id: M.marcus,
        email: 'marcus.wright@acme.demo',
        firstName: 'Marcus',
        lastName: 'Wright',
        status: 'active',
      },
    },
    {
      id: 'demo-mem-elena',
      userId: M.elena,
      organizationId: orgId,
      role: Role.MEMBER,
      createdAt: isoDaysAgo(48),
      user: {
        id: M.elena,
        email: 'elena.volkov@acme.demo',
        firstName: 'Elena',
        lastName: 'Volkov',
        status: 'active',
      },
    },
    {
      id: 'demo-mem-riley',
      userId: M.riley,
      organizationId: orgId,
      role: Role.MEMBER,
      createdAt: isoDaysAgo(41),
      user: {
        id: M.riley,
        email: 'riley.nguyen@acme.demo',
        firstName: 'Riley',
        lastName: 'Nguyen',
        status: 'active',
      },
    },
  ];

  const invites: PendingInvite[] = [
    {
      id: 'demo-invite-1',
      email: 'design.contractor@external.demo',
      role: Role.MEMBER,
      expiresAt: isoDaysAgo(-7, 23),
      createdAt: isoDaysAgo(4, 9),
    },
    {
      id: 'demo-invite-2',
      email: 'freelance.writer@agency.demo',
      role: Role.MEMBER,
      expiresAt: isoDaysAgo(-5, 23),
      createdAt: isoDaysAgo(3, 11),
    },
    {
      id: 'demo-invite-3',
      email: null,
      role: Role.ADMIN,
      expiresAt: isoDaysAgo(-3, 23),
      createdAt: isoDaysAgo(1, 14),
    },
    {
      id: 'demo-invite-4',
      email: 'security.audit@firm.demo',
      role: Role.MEMBER,
      expiresAt: isoDaysAgo(-10, 23),
      createdAt: isoDaysAgo(6, 8),
    },
    {
      id: 'demo-invite-5',
      email: 'intern.summer@university.demo',
      role: Role.MEMBER,
      expiresAt: isoDaysAgo(-14, 23),
      createdAt: isoDaysAgo(2, 16),
    },
  ];

  const activities: Activity[] = [
    {
      id: 'demo-act-proj-web',
      organizationId: orgId,
      eventType: EventType.PROJECT_CREATED,
      entityType: 'project',
      entityId: P.websiteRedesign,
      payload: { snapshot: { name: 'Website Redesign' } },
      triggeredBy: alexId,
      createdAt: isoDaysAgo(45, 9, 5),
    },
    {
      id: 'demo-act-proj-mobile',
      organizationId: orgId,
      eventType: EventType.PROJECT_CREATED,
      entityType: 'project',
      entityId: P.mobileLaunch,
      payload: { snapshot: { name: 'Mobile App Launch' } },
      triggeredBy: M.sam,
      createdAt: isoDaysAgo(38, 11, 20),
    },
    {
      id: 'demo-act-proj-ds',
      organizationId: orgId,
      eventType: EventType.PROJECT_CREATED,
      entityType: 'project',
      entityId: P.designSystem,
      payload: { snapshot: { name: 'Design System 2.0' } },
      triggeredBy: M.jordan,
      createdAt: isoDaysAgo(28, 14, 12),
    },
    {
      id: 'demo-act-proj-api',
      organizationId: orgId,
      eventType: EventType.PROJECT_CREATED,
      entityType: 'project',
      entityId: P.apiPlatform,
      payload: { snapshot: { name: 'API Platform' } },
      triggeredBy: M.priya,
      createdAt: isoDaysAgo(22, 8, 40),
    },
    {
      id: 'demo-act-proj-grw',
      organizationId: orgId,
      eventType: EventType.PROJECT_CREATED,
      entityType: 'project',
      entityId: P.growthQ2,
      payload: { snapshot: { name: 'Growth Experiments Q2' } },
      triggeredBy: M.marcus,
      createdAt: isoDaysAgo(18, 10, 25),
    },
    {
      id: 'demo-act-proj-ops',
      organizationId: orgId,
      eventType: EventType.PROJECT_CREATED,
      entityType: 'project',
      entityId: P.internalOps,
      payload: { snapshot: { name: 'Internal Ops & Tooling' } },
      triggeredBy: M.elena,
      createdAt: isoDaysAgo(12, 13, 18),
    },
    {
      id: 'demo-act-task-created-audit',
      organizationId: orgId,
      eventType: EventType.TASK_CREATED,
      entityType: 'task',
      entityId: 'demo-task-design-audit',
      payload: {
        snapshot: {
          title: 'Design system audit',
          status: TaskStatus.TODO,
          assignedTo: M.jordan,
        },
      },
      triggeredBy: alexId,
      createdAt: isoDaysAgo(21, 11, 30),
    },
    {
      id: 'demo-act-task-moved',
      organizationId: orgId,
      eventType: EventType.TASK_UPDATED,
      entityType: 'task',
      entityId: 'demo-task-design-audit',
      payload: {
        snapshot: {
          title: 'Design system audit',
          statusBefore: TaskStatus.TODO,
          status: TaskStatus.IN_PROGRESS,
        },
        changes: { status: TaskStatus.IN_PROGRESS },
      },
      triggeredBy: M.jordan,
      createdAt: isoDaysAgo(4, 14, 10),
    },
    {
      id: 'demo-act-task-beta',
      organizationId: orgId,
      eventType: EventType.TASK_CREATED,
      entityType: 'task',
      entityId: 'demo-task-beta-signup',
      payload: {
        snapshot: {
          title: 'Beta signup flow',
          assignedTo: alexId,
        },
      },
      triggeredBy: M.jordan,
      createdAt: isoDaysAgo(18, 10, 45),
    },
    {
      id: 'demo-act-task-push',
      organizationId: orgId,
      eventType: EventType.TASK_UPDATED,
      entityType: 'task',
      entityId: 'demo-task-push-cert',
      payload: {
        snapshot: {
          title: 'APNs & FCM credentials rotation',
          statusBefore: TaskStatus.TODO,
          status: TaskStatus.IN_PROGRESS,
        },
        changes: { status: TaskStatus.IN_PROGRESS },
      },
      triggeredBy: M.priya,
      createdAt: isoDaysAgo(6, 16, 22),
    },
    {
      id: 'demo-act-task-openapi',
      organizationId: orgId,
      eventType: EventType.TASK_CREATED,
      entityType: 'task',
      entityId: 'demo-task-api-openapi',
      payload: {
        snapshot: { title: 'OpenAPI 3.1 publish pipeline', assignedTo: M.priya },
      },
      triggeredBy: M.priya,
      createdAt: isoDaysAgo(15, 9, 15),
    },
    {
      id: 'demo-act-invite-batch',
      organizationId: orgId,
      eventType: EventType.INVITE_CREATED,
      entityType: 'invite',
      entityId: 'demo-invite-1',
      payload: { email: 'design.contractor@external.demo' },
      triggeredBy: alexId,
      createdAt: isoDaysAgo(4, 9, 30),
    },
    {
      id: 'demo-act-project-update-web',
      organizationId: orgId,
      eventType: EventType.PROJECT_UPDATED,
      entityType: 'project',
      entityId: P.websiteRedesign,
      payload: { snapshot: { name: 'Website Redesign' } },
      triggeredBy: M.jordan,
      createdAt: isoDaysAgo(6, 11, 0),
    },
    {
      id: 'demo-act-task-grw-started',
      organizationId: orgId,
      eventType: EventType.TASK_CREATED,
      entityType: 'task',
      entityId: 'demo-task-grw-experiment-hero',
      payload: {
        snapshot: { title: 'Experiment #142 — hero CTA copy' },
      },
      triggeredBy: M.marcus,
      createdAt: isoDaysAgo(10, 10, 0),
    },
    {
      id: 'demo-act-task-rate-limit',
      organizationId: orgId,
      eventType: EventType.TASK_CREATED,
      entityType: 'task',
      entityId: 'demo-task-api-rate-limit',
      payload: { snapshot: { title: 'Per-tenant rate limits' } },
      triggeredBy: M.priya,
      createdAt: isoDaysAgo(9, 8, 45),
    },
    {
      id: 'demo-act-task-ds-tokens',
      organizationId: orgId,
      eventType: EventType.TASK_UPDATED,
      entityType: 'task',
      entityId: 'demo-task-ds-tokens',
      payload: {
        snapshot: {
          title: 'Semantic color tokens (dark mode)',
          statusBefore: TaskStatus.TODO,
          status: TaskStatus.IN_PROGRESS,
        },
        changes: { status: TaskStatus.IN_PROGRESS },
      },
      triggeredBy: M.jordan,
      createdAt: isoDaysAgo(5, 15, 30),
    },
    {
      id: 'demo-act-member-priya',
      organizationId: orgId,
      eventType: EventType.MEMBER_JOINED,
      entityType: 'member',
      entityId: M.priya,
      payload: { snapshot: { name: 'Priya Shah' } },
      triggeredBy: M.priya,
      createdAt: isoDaysAgo(62, 10, 0),
    },
    {
      id: 'demo-act-task-ops-runbook',
      organizationId: orgId,
      eventType: EventType.TASK_CREATED,
      entityType: 'task',
      entityId: 'demo-task-ops-runbook',
      payload: { snapshot: { title: 'Incident runbook — payment failures' } },
      triggeredBy: M.elena,
      createdAt: isoDaysAgo(9, 12, 0),
    },
    {
      id: 'demo-act-task-cms',
      organizationId: orgId,
      eventType: EventType.TASK_UPDATED,
      entityType: 'task',
      entityId: 'demo-task-cms-migration',
      payload: {
        snapshot: {
          title: 'CMS content migration dry run',
          statusBefore: TaskStatus.TODO,
          status: TaskStatus.IN_PROGRESS,
        },
        changes: { status: TaskStatus.IN_PROGRESS },
      },
      triggeredBy: M.sam,
      createdAt: isoDaysAgo(3, 10, 20),
    },
    {
      id: 'demo-act-task-perf-done',
      organizationId: orgId,
      eventType: EventType.TASK_UPDATED,
      entityType: 'task',
      entityId: 'demo-task-perf-budget',
      payload: {
        snapshot: {
          title: 'Mobile perf budget — cold start',
          statusBefore: TaskStatus.IN_PROGRESS,
          status: TaskStatus.DONE,
        },
        changes: { status: TaskStatus.DONE },
      },
      triggeredBy: M.sam,
      createdAt: isoDaysAgo(11, 17, 0),
    },
    {
      id: 'demo-act-task-wcag',
      organizationId: orgId,
      eventType: EventType.TASK_CREATED,
      entityType: 'task',
      entityId: 'demo-task-accessibility-audit',
      payload: { snapshot: { title: 'WCAG 2.2 AA audit remediation' } },
      triggeredBy: alexId,
      createdAt: isoDaysAgo(16, 9, 0),
    },
    {
      id: 'demo-act-task-referral',
      organizationId: orgId,
      eventType: EventType.TASK_CREATED,
      entityType: 'task',
      entityId: 'demo-task-grw-referral',
      payload: { snapshot: { title: 'Referral loop v2 — double-sided reward' } },
      triggeredBy: M.marcus,
      createdAt: isoDaysAgo(8, 14, 0),
    },
    {
      id: 'demo-act-task-deep-links',
      organizationId: orgId,
      eventType: EventType.TASK_CREATED,
      entityType: 'task',
      entityId: 'demo-task-deep-links',
      payload: { snapshot: { title: 'Universal links & deferred deep linking' } },
      triggeredBy: M.sam,
      createdAt: isoDaysAgo(4, 11, 30),
    },
  ];

  const notifications: Notification[] = [
    {
      id: 'demo-notif-1',
      userId: alexId,
      organizationId: orgId,
      type: 'task_assigned',
      title: 'Assigned to Beta signup flow',
      message: 'Jordan Lee assigned you to Beta signup flow',
      entityType: 'task',
      entityId: 'demo-task-beta-signup',
      read: false,
      actorId: M.jordan,
      createdAt: isoDaysAgo(0, 9),
      actor: { id: M.jordan, firstName: 'Jordan', lastName: 'Lee' },
    },
    {
      id: 'demo-notif-2',
      userId: alexId,
      organizationId: orgId,
      type: 'task_updated',
      title: 'Design system audit moved',
      message: 'Jordan moved Design system audit to In progress',
      entityType: 'task',
      entityId: 'demo-task-design-audit',
      read: false,
      actorId: M.jordan,
      createdAt: isoDaysAgo(2, 14),
      actor: { id: M.jordan, firstName: 'Jordan', lastName: 'Lee' },
    },
    {
      id: 'demo-notif-3',
      userId: alexId,
      organizationId: orgId,
      type: 'member_joined',
      title: 'Welcome Sam',
      message: 'Sam Rivera joined Acme Product Team',
      entityType: 'organization',
      entityId: orgId,
      read: true,
      actorId: M.sam,
      createdAt: isoDaysAgo(88, 12),
      actor: { id: M.sam, firstName: 'Sam', lastName: 'Rivera' },
    },
    {
      id: 'demo-notif-4',
      userId: alexId,
      organizationId: orgId,
      type: 'task_assigned',
      title: 'CMS migration',
      message: 'Sam Rivera assigned you to review CMS migration dry run',
      entityType: 'task',
      entityId: 'demo-task-cms-migration',
      read: false,
      actorId: M.sam,
      createdAt: isoDaysAgo(1, 11),
      actor: { id: M.sam, firstName: 'Sam', lastName: 'Rivera' },
    },
    {
      id: 'demo-notif-5',
      userId: alexId,
      organizationId: orgId,
      type: 'task_updated',
      title: 'Rate limits',
      message: 'Priya Shah commented on Per-tenant rate limits',
      entityType: 'task',
      entityId: 'demo-task-api-rate-limit',
      read: false,
      actorId: M.priya,
      createdAt: isoDaysAgo(0, 18),
      actor: { id: M.priya, firstName: 'Priya', lastName: 'Shah' },
    },
    {
      id: 'demo-notif-6',
      userId: alexId,
      organizationId: orgId,
      type: 'task_assigned',
      title: 'Growth experiment',
      message: 'Marcus Wright added you as watcher on Experiment #142',
      entityType: 'task',
      entityId: 'demo-task-grw-experiment-hero',
      read: true,
      actorId: M.marcus,
      createdAt: isoDaysAgo(3, 10),
      actor: { id: M.marcus, firstName: 'Marcus', lastName: 'Wright' },
    },
    {
      id: 'demo-notif-7',
      userId: alexId,
      organizationId: orgId,
      type: 'member_joined',
      title: 'Priya joined',
      message: 'Priya Shah joined Acme Product Team',
      entityType: 'organization',
      entityId: orgId,
      read: true,
      actorId: M.priya,
      createdAt: isoDaysAgo(62, 9),
      actor: { id: M.priya, firstName: 'Priya', lastName: 'Shah' },
    },
    {
      id: 'demo-notif-8',
      userId: alexId,
      organizationId: orgId,
      type: 'task_updated',
      title: 'Push certificates',
      message: 'Priya Shah updated APNs & FCM credentials rotation',
      entityType: 'task',
      entityId: 'demo-task-push-cert',
      read: false,
      actorId: M.priya,
      createdAt: isoDaysAgo(1, 8),
      actor: { id: M.priya, firstName: 'Priya', lastName: 'Shah' },
    },
    {
      id: 'demo-notif-9',
      userId: alexId,
      organizationId: orgId,
      type: 'task_assigned',
      title: 'Admin audit log',
      message: 'Elena Volkov assigned you to Admin action audit log UI',
      entityType: 'task',
      entityId: 'demo-task-ops-admin-audit',
      read: true,
      actorId: M.elena,
      createdAt: isoDaysAgo(5, 14),
      actor: { id: M.elena, firstName: 'Elena', lastName: 'Volkov' },
    },
    {
      id: 'demo-notif-10',
      userId: alexId,
      organizationId: orgId,
      type: 'task_updated',
      title: 'OpenAPI pipeline',
      message: 'OpenAPI 3.1 publish pipeline moved to In progress',
      entityType: 'task',
      entityId: 'demo-task-api-openapi',
      read: true,
      actorId: M.priya,
      createdAt: isoDaysAgo(4, 16),
      actor: { id: M.priya, firstName: 'Priya', lastName: 'Shah' },
    },
    {
      id: 'demo-notif-11',
      userId: alexId,
      organizationId: orgId,
      type: 'task_assigned',
      title: 'Support macros',
      message: 'Riley Nguyen requested review on Support macro refresh',
      entityType: 'task',
      entityId: 'demo-task-ops-macros',
      read: false,
      actorId: M.riley,
      createdAt: isoDaysAgo(0, 15),
      actor: { id: M.riley, firstName: 'Riley', lastName: 'Nguyen' },
    },
    {
      id: 'demo-notif-12',
      userId: alexId,
      organizationId: orgId,
      type: 'task_updated',
      title: 'Dark mode tokens',
      message: 'Jordan updated Semantic color tokens (dark mode)',
      entityType: 'task',
      entityId: 'demo-task-ds-tokens',
      read: false,
      actorId: M.jordan,
      createdAt: isoDaysAgo(1, 10),
      actor: { id: M.jordan, firstName: 'Jordan', lastName: 'Lee' },
    },
  ];

  return {
    user,
    organizations,
    projects,
    tasks,
    memberships,
    invites,
    activities,
    notifications,
  };
}
